### PR TITLE
Add Algolia friendly Search Index plugin

### PR DESCRIPTION
**Pull request by lukeocodes**
Based on Swyx's search index plugin, tweaked it for Algolia format search index.

### CODE REVIEW

**Comment by ehmicky** [comment]
Hi @lukeocodes,

Thanks a lot for this plugin! :tada: 

`netlify-plugin-search-index` was based on an older version of Build plugins. I have sent several PRs to this plugin, which have not been merged yet (https://github.com/sw-yx/netlify-plugin-search-index/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc). Unfortunately, this carried over to your plugin: would it be possible for you to implement those changes in your plugin? We have removed support for some deprecated syntax, which those PRs meant to address. 

Thanks a lot again, please let me know if you need any help :pray:

**Comment by lukeocodes** [comment]
I saw your PRs actually. Sure, I can do this no problem! I'll leave another comment here once they're done!

**Comment by lukeocodes** [comment]
hey, @ehmicky I've made those changes. please let me know if there is anything else :)

**Comment by ehmicky** [comment]
This is looking great! Just need to bump the `version` in the PR :)

**Comment by lukeocodes** [comment]
whoops, that changed a little while ago! my mistake! updated to the latest representing those changes

**Pull request merged**
