### PR TITLE
Adds Dareboost plugin

### PR DESCRIPTION
**Pull request by borisschapira**
This is a plugin for Dareboost customers, so that they can automatically add an event matching the successful build into their monitoring graph, and launch new pages analyses on their target.

Most of the configuration is done through `inputs`, except for the Dareboost API token that you need to define in an env. variable (I didn't want people committing their token by mistake on a public repo). The token is not logged during the build ([example](https://app.netlify.com/sites/borisschapira/deploys/5ed17a00e9063e00061ca9c6)).

**Next:** trying to understand how to configure, in this `netlify.toml` file, different plugin inputs for different branches (or restrict the execution of a plugin to one branch only).

Thanks for contributing the the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [x] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers might need for testing.

==> https://app.netlify.com/sites/borisschapira/deploys/5ed17a00e9063e00061ca9c6

### CODE REVIEW

**Comment by ehmicky** [comment]
This is looking great, thanks @borisschapira!

I found two minor issues filed [here](https://github.com/borisschapira/netlify-build-plugin-dareboost/issues?q=is%3Aissue+is%3Aopen+author%3Aehmicky+sort%3Aupdated-desc).

About branch-specific logic: we are working on it, but this is not available yet unfortunately. The feature request is [here](https://github.com/netlify/build/issues/1169).

Is there anyway the plugin could show the speed test result as well? If you use the [`utils.status.show()`](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#logging) method, those would show in the deploy summary, which might be a nice experience. What do you think?

**Comment by borisschapira** [comment]
Hi @ehmicky, thanks for this quick feedback! I fixed the issues.

> Is there anyway the plugin could show the speed test result as well?

The starting of the performance test after the API call is asynchronous. To get the result, the API must be called back every X seconds until a result is obtained. I could have done it, but I didn't want to penalize the build times of the users.

**Comment by ehmicky** [comment]
Thanks @borisschapira!

> The starting of the performance test after the API call is asynchronous. To get the result, the API must be called back every X seconds until a result is obtained. I could have done it, but I didn't want to penalize the build times of the users.

Is there a web URL that could be displayed to users so they can directly click on it and see the analysis progress?

**Comment by borisschapira** [comment]
Great idea. I'll look into it. I need to check if, using `utils.status.show()`, we can display several clickables URLs in the Summary (one per launched test).

**Comment by ehmicky** [comment]
Great! The documentation of `utils.status.show()` is [here](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#logging).

I am not sure whether the URL will be clickable. I would recommend putting either:
  - all the URLs in the `summary` property
  - the main URL in the `summary` property, and the others in `text` (which is a dropdown details box).

**Comment by borisschapira** [comment]
Thanks to the documention, I went for this:

Capture d’écran 2020-05-29 à 23 16 15

However, this only seems to work in `netlify-cli`. Nothing appears [in a Netlify build](https://app.netlify.com/sites/borisschapira/deploys/5ed17a00e9063e00061ca9c6). Any idea why, @ehmicky?

**Comment by ehmicky** [comment]
This is because this feature is still a WIP, but should be fully available in the UI soon! :)

**Comment by ehmicky** [comment]
@borisschapira branch-specific configuration has been implemented! :tada: 

More information in [this comment](https://github.com/netlify/build/issues/1169#issuecomment-818017760). Please let me know if this works as expected.

**Pull request merged**
