### PR TITLE
feat: publish `plugins.json` to our CDN

### PR DESCRIPTION
**Pull request by ehmicky**
Part of https://github.com/netlify/pod-the-builder/issues/106

This is publishing `plugins.json` to our CDN.
[Link to `plugins.json`](https://5fbffc01d0654600074c5cb8--netlify-plugins.netlify.app/plugins.json).
Once merged to `master`, this will be available at https://netlify-plugins.netlify.app/plugins.json

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
Looks good. Our UI is not read the plugins json from this repo right? If it does we would need to update it too

**Comment by ehmicky** [comment]
It is! I just fixed it :)
https://github.com/netlify/netlify-react-ui/blob/8423ca5cc69cd03960633bc3c115ff52f1d7d24b/src/actions/plugins.js#L9

**Review by erezrokah — APPROVED** [review]

**Comment by ehmicky** [comment]
Front-end link still working after merge: https://raw.githubusercontent.com/netlify/plugins/master/plugins.json

**Comment by erezrokah** [comment]
Added a `low-risk` label - we're keeping the old file so this should be ok.

**Comment by ehmicky** [comment]
Follow-up: https://github.com/netlify/plugins/pull/179, https://github.com/netlify/netlify-react-ui/pull/6408

**Pull request merged**
