### PR TITLE
Add plugin "netlify-plugin-ttl-cache"

### PR DESCRIPTION
**Pull request by andyrichardson**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [x] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/main/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/main/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
Functionality is tested via the following steps:
 - clone [this repo](https://github.com/andyrichardson/netlify-plugin-ttl-cache-example)
 - build the project (`netlify build`)
 - make note of build output assets (e.g. `2.[hash].chunk.js`)
 - Edit content in `Lazy.js`
 - build the project (`netlify build`)
 - Check that previous (hashed) build output assets are still in `build` folder

Here is the [latest public deployment](https://app.netlify.com/sites/netlify-plugin-ttl-cache/deploys/612d1469171fd3000710ee78).

### CODE REVIEW

**Comment by JGAntunes** [comment]
Hey @andyrichardson 👋

Thank you for your plugin contribution!

Everything looks alright 👍 From reviewing the code though I do have one quick question. You're purposefully leaving behind the restored filtered cache in `inputs.path` -https://github.com/andyrichardson/netlify-plugin-ttl-cache/blob/54127d8050d92f1335d37c7666c3161aafa82f11/src/index.js#L29 - for the build stage, is this intended? I figure so but just wanted to double check, since you also restore it from the `tmp` dir after build (and I believe the main goal for the plugin is to restore cache for the deploy stage?)

**Comment by andyrichardson** [comment]
> Hey @andyrichardson 
> 
> Thank you for your plugin contribution!
> 
> Everything looks alright  From reviewing the code though I do have one quick question. You're purposefully leaving behind the restored filtered cache in `inputs.path` -https://github.com/andyrichardson/netlify-plugin-ttl-cache/blob/54127d8050d92f1335d37c7666c3161aafa82f11/src/index.js#L29 - for the build stage, is this intended? I figure so but just wanted to double check, since you also restore it from the `tmp` dir after build (and I believe the main goal for the plugin is to restore cache for the deploy stage?)

@JGAntunes thanks for the response!

My assumption was that the deploy process runs in a stateless environment - is that not the case? More than happy to clean up temporary files if that's not done automatically :+1:

**Comment by ehmicky** [comment]
Hi @andyrichardson, thanks a lot for this plugin!
In parallel with @JGAntunes's review, I have [created a few issues in your repository](https://github.com/andyrichardson/netlify-plugin-ttl-cache/issues/created_by/ehmicky) to discuss some potential improvements. Please let me know what you think!

**Comment by erezrokah** [comment]
Thanks @andyrichardson for you contribution, and @ehmicky and @JGAntunes for reviewing.

Closing this as it seems to have gone stale. Please feel free to submit a new PR after addressing the issues mentioned

**Pull request closed without merging**
