### PR TITLE
Add Next.js cache plugin

### PR DESCRIPTION
**Pull request by karlhorky**

### CODE REVIEW

**Comment by ehmicky** [comment]
Hi @karlhorky!

It seems like this plugin [is already present](https://github.com/netlify/plugins/blob/954c14c7ef582c82186dedaa91afa028a089f751/plugins.json#L44) in our list?

**Comment by karlhorky** [comment]
@ehmicky Oh sorry, didn't see that - was scanning alphabetically. I've changed this PR just to change the order of this existing plugin to be alphabetical - does that sound acceptable to you?

**Comment by ehmicky** [comment]
Sounds good! However the `README.md` is generated from the `plugins.json`.

You should update the `plugins.json` then run `npm run docs` to update the `README.md` :)

**Comment by karlhorky** [comment]
Don't want to have to clone the project and install the tooling, so just edited by hand. All good now?

**Comment by ehmicky** [comment]
Thanks.

**Comment by karlhorky** [comment]
Glad to help, thanks for the merge!

**Pull request merged**
