### PR TITLE
Add ENV plugin

### PR DESCRIPTION
**Pull request by cball**
This plugin allows context/branch level ENV variables, allowing a user to override ENV vars without exposing them in `netlify.toml`.

### CODE REVIEW

**Comment by verythorough** [comment]
This is awesome, @cball ! Can I suggest giving your plugin a more descriptive name? "Env" could mean anything related to env vars. Maybe something like Env Context Prefixer/env-context-prefixer?

**Comment by cball** [comment]
@verythorough sure thing. What about `Context Specific Env Vars / context-specific-env-vars` since it can work with prefixes or suffixes?

I'm fine with `Env Context Prefixer/env-context-prefixer` as well. Whatever you suggest.

**Comment by verythorough** [comment]
@cball your idea sounds great! I totally skipped over the suffix part of the description 🤦 
If you'd like something a little shorter, you could consider `contextual` instead of `context-specific`, but it's your plugin, so it's up to you!

**Comment by cball** [comment]
@verythorough 👍 I like that. <insert comment about naming being hard> 😂

**Comment by cball** [comment]
I've renamed the package and unpublished the old one. Unfortunately, https://www.npmjs.com/package/netlify-plugin-contextual-env is currently throwing a 503. I'm hoping that will resolve itself shortly.

**Comment by cball** [comment]
@ehmicky quick update - I went ahead and removed setting `process.env` directly until you have time to work on https://github.com/netlify/build/issues/1129.

We could release it now with more limited support, or wait until we can set `process.env`. Totally up to you all.

**Comment by ehmicky** [comment]
Hi @cball, https://github.com/netlify/build/issues/1129 is done!

You can now modify `process.env` inside Build plugins and it will be modified as well inside `build.command` (and also inside other Build plugins). 

Based on this, would you like to release a version with just `process.env` and not `.env` file instead?

**Comment by cball** [comment]
awesome work @ehmicky! I'll circle back to that as soon as I can, hopefully later today or early tomorrow.

**Comment by cball** [comment]
@ehmicky just released 0.3.0 which sets `process.env` directly. Appreciate your help with this!

**Comment by ehmicky** [comment]
This is awesome! This plugin is super useful.

**Pull request merged**
