### PR TITLE
Add webmentions plugin

### PR DESCRIPTION
**Pull request by CodeFoodPixels**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [ ] Adding a plugin
- [x] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers might need for testing.
https://app.netlify.com/sites/lukeb-co-uk/deploys/60393a3a651aff0007f0f7a7

### CODE REVIEW

**Comment by CodeFoodPixels** [comment]
@JGAntunes Thanks for dropping some suggestions and changes on my repo. Once you're happy, I'll publish a new version and update the version in this change

**Comment by JGAntunes** [comment]
Thanks for your contribution @CodeFoodPixels and for addressing those super quick also 😄 I think we're good, once the new version is out and updated in this PR we can merge it 👍

**Comment by CodeFoodPixels** [comment]
Awesome, the new version is published and I've updated it here!

**Review by JGAntunes — APPROVED** [review]
👍

**Comment by JGAntunes** [comment]
It is now available directly in the Netlify UI

image

Once again, thanks @CodeFoodPixels 👍

**Pull request merged**
