### PR TITLE
feat: add Ghost Inspector Netlify plugin

### PR DESCRIPTION
**Pull request by simpixelated**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [x] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/main/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/main/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
https://app.netlify.com/sites/simpixelated/deploys/6082fd41ec751b7a69691f2e - for your own testing you will need a free [Ghost Inspector account](https://app.ghostinspector.com/account/create) and create a least one suite + test.

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @simpixelated and sorry for the delay in reviewing this.
I opened a few issues on the plugin's repo for your consideration.

Also, more of a general question - the plugin blocks until the tests finish running correct?
How long does it take to a common test suite to finish? Is there a chance of hitting the build time limit of 15 minuets for the entire build?

I wonder if it's worth adding an option to just trigger a test suite instead of waiting for it to complete.
Adding some kind of progress log can help too.

Also, would it make sense to run all suites? If not and a suite is linked to a site - can we know which one in the plugin so we can remove the need to configure `GHOST_INSPECTOR_SUITE` (e.g. use `process.env.SITE_NAME`)?

**Comment by simpixelated** [comment]
Hi @erezrokah! No problem on the delay and I appreciate your feedback. I'll address the issues in the repo.

> Also, more of a general question - the plugin blocks until the tests finish running correct?
> How long does it take to a common test suite to finish? Is there a chance of hitting the build time limit of 15 minuets for the entire build?

Our test runs are limited to 10 minutes so there shouldn't be an issue there.

> I wonder if it's worth adding an option to just trigger a test suite instead of waiting for it to complete.
> Adding some kind of progress log can help too.

That's a great idea! Is there any reason not to just make that the default? I suppose then it wouldn't be possible to "fail" the plugin if a test failed, but as long as the progress log + GitHub updates are clear, I don't know if that's necessary. My preference is to keep the user setup and code logic as simple as possible.

> Also, would it make sense to run all suites? If not and a suite is linked to a site - can we know which one in the plugin so we can remove the need to configure `GHOST_INSPECTOR_SUITE` (e.g. use `process.env.SITE_NAME`)?

A large portion of our users test multiple sites; suites are the typical way to organize that. So for that reason I don't think it makes sense to run all suites.

Since the plugin only allows a single suite ID, it does force the user to organize their tests into a single suite for their Netlify site. So you're right that in practice the suite would be linked to a site. But because suites can have any name, it would still require the user to update their suite name to match what is set in Netlify, so it doesn't really simplify the user setup. Plus suite names are not unique, so it could lead to confusion by not using the unique ID.

**Comment by erezrokah** [comment]
Hi @simpixelated, thank you for the quick follow up.

> Our test runs are limited to 10 minutes so there shouldn't be an issue there.

🎉 

> That's a great idea! Is there any reason not to just make that the default? I suppose then it wouldn't be possible to "fail" the plugin if a test failed, but as long as the progress log + GitHub updates are clear, I don't know if that's necessary. My preference is to keep the user setup and code logic as simple as possible.

That's a product decision I'll leave to you. Triggering instead of waiting does have the benefit of using less build minuets on the Netlify side, so making it the default makes sense to me, especially when users can see the results as GitHub statues.

> Since the plugin only allows a single suite ID, it does force the user to organize their tests into a single suite for their Netlify site. So you're right that in practice the suite would be linked to a site. But because suites can have any name, it would still require the user to update their suite name to match what is set in Netlify, so it doesn't really simplify the user setup. Plus suite names are not unique, so it could lead to confusion by not using the unique ID.

Cool that makes sense, thank you for clarifying.

Let me know if you want to change the default behavior, if not we can move forward with the current one.

**Comment by simpixelated** [comment]
@erezrokah I tested out just triggering tests and it doesn't really work in practice. The git commit status updates are within this code, so exiting before a Ghost Inspector test finishes means the commit statuses never get updated. We could disable that logic if the test exits early, but it seems confusing to have an optional feature that depends on another optional feature. Plus, without the git updates, the only way to know if the test passed or failed is to login to our app, which would reduce the plugin to barely adding any value.

I've resolved the issues you added to the repo. We'll need to do a release version, which I assume should happen before merging anything into the plugin list.

**Comment by erezrokah** [comment]
> @erezrokah I tested out just triggering tests and it doesn't really work in practice. The git commit status updates are within this code, so exiting before a Ghost Inspector test finishes means the commit statuses never get updated. We could disable that logic if the test exits early, but it seems confusing to have an optional feature that depends on another optional feature. Plus, without the git updates, the only way to know if the test passed or failed is to login to our app, which would reduce the plugin to barely adding any value.

Makes sense thank you for checking. A possible solution is to send the commit hash to the service and have it set the status checks. That way users don't need to configure a GitHub token in the plugin (they'll need to do it via the service).
I think this is out of scope for now.

> I've resolved the issues you added to the repo. We'll need to do a release version, which I assume should happen before merging anything into the plugin list.

Correct. Once you have the new release ready you can update this PR.

**Review by erezrokah — APPROVED** [review]
Hi @simpixelated, this looks good, thank you for following up with the changes.

Let me know when you're ready and I'll merge the PR

**Comment by simpixelated** [comment]
I'm ready @erezrokah! Please merge

**Comment by erezrokah** [comment]
FYI, this is now available in our UI plugins list

**Pull request merged**
