### PR TITLE
Added a JavaScript Obfuscator Netlify build plugin

### PR DESCRIPTION
**Pull request by iamanishroy**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [✓] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [✓] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [✓] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [✓] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers might need for testing.

### CODE REVIEW

**Comment by JGAntunes** [comment]
Hey @iamanishroy 👋 thanks for your contribution! I'll be looking into reviewing your plugin but meanwhile could you provide a test plan for your plugin? Essentially a link to a netlify build using your plugin 👍

**Comment by iamanishroy** [comment]
Thanks, @JGAntunes  for replying. Though I have a doubt regarding the test plan but are you looking for this(https://github.com/iamanishroy/netlify-plugin-js-obfuscator-test)?

**Comment by JGAntunes** [comment]
Yeah that will do 👍 for reference I also ended up doing some testing myself - https://app.netlify.com/sites/test-antunes-yolo/deploys/6012b0053fbe8300075a92c2

Just one more suggestion. Given the performance impact that obfuscating JS code can have (as is mentioned in the package README - https://github.com/javascript-obfuscator/javascript-obfuscator#warning-important) we were wondering if you would be willing to add some sort of warning like this to your own package README? For example:

```md
# netlify-plugin-js-obfuscator

A Netlify Build plugin to extract and obfuscate your JavaScript Source Code (...)

(...)

The example of obfuscated code: [github.com](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/examples/javascript-obfuscator.js)

## :warning: Important
As describe in the [`js-obfuscator` package](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/README.md#warning-important), code obfuscation may impact your website's performance.
```

Other than that I believe we only need to address the conflicts in this PR (rebase with master) and we should be good to go 👍

**Comment by iamanishroy** [comment]
Ok 👍

**Comment by iamanishroy** [comment]
Done!! Anything else to do?

**Comment by iamanishroy** [comment]
@JGAntunes do I need to do anything else?

**Review by JGAntunes — APPROVED** [review]

**Comment by JGAntunes** [comment]
All good @iamanishroy 👍 going to merge this. Meanwhile I've validated that the latest version `1.0.20` is present in npm and matches what we expect, however seems like you haven't pushed the changes to git - https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/main/package.json#L3 - I would advise you to do so 👍

Thank you for your contribution 🎉

**Comment by JGAntunes** [comment]
image

**Comment by iamanishroy** [comment]
Thank you @JGAntunes for considering my work. It means a lot to me.

**Pull request merged**
