### PR TITLE
Add netlify-plugin-pagewatch

### PR DESCRIPTION
**Pull request by lpellis**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [x] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [x ] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers might need for testing.

https://app.netlify.com/sites/deepabstractart/deploys/5f920a9ccced07000816a96a

### CODE REVIEW

**Review by ehmicky — CHANGES_REQUESTED** [review]
This is look great, thanks @lpellis!

I have added a small comment at https://github.com/pagewatchdev/netlify-plugin-pagewatch/issues/1, but it looks all good otherwise :+1: 

Please note than `onSuccess` is still currently performed before deploy. We are currently working on making it happen after deploy, and hope to get this working soon. See https://github.com/netlify/plugins/issues/140#issuecomment-713512141

**Comment by lpellis** [comment]
Those changes to the `on_success` will be very welcome, currently I just retry the preview_url until the site is live, but I was not sure how to correctly handle production deploys, so I just hardcoded a 15 seconds delay to give the deploy time.  Once the new behaviour is out I can remove that :)

I'l push the requested changes soon.

**Comment by lpellis** [comment]
I pushed the changes, here is a build on the latest 1.0.4 
https://app.netlify.com/sites/deepabstractart/deploys/5f93265cdf4dc500074f7ed3

**Review by ehmicky — APPROVED** [review]

**Comment by ehmicky** [comment]
:tada:

**Pull request merged**
