### PR TITLE
feat: enforce consistent plugins names

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes https://github.com/netlify/plugins/issues/208

Keeping this open as a draft to get visibility as we probably want to tell plugin authors before/if we merge this.

### CODE REVIEW

**Comment by erezrokah** [comment]
@ehmicky going to add another commit to change names to `sentence case`

**Comment by erezrokah** [comment]
@ehmicky I removed the casing test as to check for `sentence case` we need a list of known words (like `Instagram`, `Netlify` and others we can't know in advance).

**Review by ehmicky — APPROVED** [review]
Looks good! :+1: 
Could we enforce that the first letter is uppercase? This should work regardless of whether this is a proper or common noun.

**Comment by erezrokah** [comment]
> Could we enforce that the first letter is uppercase? This should work regardless of whether this is a proper or common noun.

Yes we can! Done in https://github.com/netlify/plugins/pull/209/commits/745429bcadadbe00a5d4ffc81a30b7f6493b55d5

**Pull request merged**
