### PR TITLE
Add netlify-plugin-out-of-minutes

### PR DESCRIPTION
**Pull request by williamjacksn**
I wrote a build plugin that will cancel a build if there are not enough build minutes left.

### CODE REVIEW

**Comment by williamjacksn** [comment]
I would appreciate any feedback you might have on my plugin. Thanks!

**Comment by ehmicky** [comment]
Thanks for submitting this @williamjacksn!

I would just like to confirm about one thing: this plugin requires user to add a Netlify access token as a `NETLIFY_AUTH_TOKEN` environment variable. I would like to confirm with @erquhart and @verythorough the following: could this be a security concern? Every library used by the Build could access this environment variable.

One thing we could do to see this would be to provide a Netlify access token to Build plugins. This would also make it easier for the ones that need it, without requiring user configuration. Netlify Build already has such a token but it's scoped to very endpoints. 

Also, we might want to expose a JavaScript client instance to Build plugins to prevent doing direct API calls with `node-fetch` or other library.

I believe https://github.com/netlify/build/issues/557 would fix those problems.

**Comment by williamjacksn** [comment]
That's a good point about the auth token as environment variable. I saw that you had already done some work with including a client already, but that was on hold, so this is what I came up with.

I don't mind if this sits around and is not merged into the plugin list for now. I will also add a security note on the plugin repo describing the implications of putting the auth token in the environment.

**Comment by williamjacksn** [comment]
Closing this request for now.

**Comment by ehmicky** [comment]
Sorry for the delay @williamjacksn! We'll come back to you as soon as we've got API access working.

**Pull request closed without merging**
