### PR TITLE
bump the version of netlify-plugin-inline-functions-env

### PR DESCRIPTION
**Pull request by bencao**
The updates include a new input named "buildEvent". Details can be viewed on https://github.com/bencao/netlify-plugin-inline-functions-env/blob/master/CHANGELOG.md.

Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [ ] Adding a plugin
- [x] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plans**

- With the new `exclude` flag: https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5fa27bba25b696000800ef72
- With the new `include` flag: https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5fa27a79e43634000735edbc
- With no `include` or `exclude` flags: https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5fa27bf6274dca00070eb88d

Also unit test is introduced and included in https://github.com/bencao/netlify-plugin-inline-functions-env/blob/master/test/index.test.js

### CODE REVIEW

**Review by ehmicky — CHANGES_REQUESTED** [review]
Hi @bencao,

Thanks!
It looks like `1.0.5` is not including the [`utils.functions.list()` change](https://github.com/bencao/netlify-plugin-inline-functions-env/commit/8e3f1e1d419bb5ccaef1a6abd22e4bf41e469a3d). This can be shown in the diff [here](https://diff.intrinsic.com/netlify-plugin-inline-functions-env/1.0.4/1.0.5) but also when installing the plugin locally. 
Would it be possible to make a `1.0.6` release that includes it? Thanks!

**Comment by bencao** [comment]
@ehmicky Just published 1.0.6 with utils.functions.list() change and two more feature flags. Test plan updated to point to the new test deployment for 1.0.6.

**Comment by ehmicky** [comment]
Hi @bencao, thanks a lot!
`1.0.6` is accidentally removing support for Node 10 users. I have added an issue for it [here](https://github.com/bencao/netlify-plugin-inline-functions-env/issues/16).

**Comment by bencao** [comment]
@ehmicky v1.0.8 which fixed previous regression and also added test pipelines for multiple node versions were published.

**Review by ehmicky — APPROVED** [review]
:tada:

**Pull request merged**
