### PR TITLE
Add image optim plugin

### PR DESCRIPTION
**Pull request by chrisdwheatley**
This PR adds the image optim plugin to the list of Netlify plugins. It also fixes an issue with the link to the `plugins.json` file not working from the readme.

### CODE REVIEW

**Comment by ehmicky** [comment]
Hi @chrisdwheatley,

This is great!

We have updated some things in how Build plugins are built. The new documentation is [here](https://github.com/netlify/build/blob/master/README.md). There is also a list of common gotchas [here](https://github.com/netlify/build/issues/1068#issuecomment-605276244) which is helpful to go through.

I think this plugin might be using the old format. Do you think it would be possible for you to update it? Thanks a lot for this awesome plugin!

**Comment by chrisdwheatley** [comment]
Thanks, unfortunately I've not had chance to take a look at how things have changed recently but will take a look over the weekend and try to get things up to date.

**Comment by ehmicky** [comment]
Great! Feel free to ask me any questions.

**Comment by ehmicky** [comment]
Hi @chrisdwheatley, I have put up [some PRs](https://github.com/chrisdwheatley/netlify-plugin-image-optim/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) to help out! :)

**Comment by chrisdwheatley** [comment]
I've updated and tested my plugin based on the changes you PR'd @ehmicky and I've published version `0.3.0`. Hopefully that covers everything needed to be added to the list :)

The comment I mentioned originally about the readme link is no longer an issue just FYI.

**Comment by ehmicky** [comment]
Thanks @chrisdwheatley!
This is looking good. This repository's list of files has changed, which seemed to have messed up this PR diff a little. Would it be possible to only include the addition of this plugin to `plugins.json`.
Thanks!

**Pull request merged**
