### PR TITLE
Update Nimbella plugins version.

### PR DESCRIPTION
**Pull request by rabbah**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [ ] Adding a plugin
- [x] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers might need for testing.

https://app.netlify.com/sites/unruffled-goodall-33e532/deploys/602c52a96ce2a32f0cdf114b

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Hi @rabbah, does this update include any breaking changes?
I couldn't figure it out from https://github.com/nimbella/netlify-plugin-nimbella/compare/v1.8.0...v2.0.0

**Comment by rabbah** [comment]
There is a breaking change in this version, removing some plugin.input properties in favor of a project manifest that allows for more fine grained control. I will backward compatibility with a deprecation notice (similar to [this example](https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/dcab832d66621963305f2544a08cf68ec1c7cb70/src/config.js#L33)) and amend the version in this PR when ready.

**Comment by rabbah** [comment]
I've updated the version to 2.1.0 which is backward compatible and issues deprecation as suggested.

New logs:
- Using `project.yml`: https://app.netlify.com/sites/whiskers/deploys/60303eb4d04a190007e23102
- Netlify functions: https://app.netlify.com/sites/stoic-benz-37eafd/deploys/60304f17ffd35700084a18e0

**Review by erezrokah — APPROVED** [review]
Thanks for the quick follow up @rabbah!

**Pull request merged**
