### PR TITLE
Add netlify-plugin-submit-sitemap

### PR DESCRIPTION
**Pull request by cdeleeuwe**
Thanks for contributing the the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [x] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**
https://app.netlify.com/sites/netlify-plugin-submit-sitemap/deploys/5ed72acda7c8231e23f5c8a4

### CODE REVIEW

**Comment by ehmicky** [comment]
Hi @cdeleeuwe,

Thanks for this new plugin! :tada: 

I added few comments [as issues](https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/issues?q=is%3Aissue+is%3Aopen+author%3Aehmicky+sort%3Aupdated-desc) to the repository. Please let me know what you think! :)

**Comment by cdeleeuwe** [comment]
@ehmicky Thanks a lot for looking into it and suggesting the improvements :). All makes sense.. will make the adjustments.

**Comment by cdeleeuwe** [comment]
@ehmicky I made the adjustments. 

As example here is a failed plugin:
https://app.netlify.com/sites/netlify-plugin-submit-sitemap/deploys/5ed92d12f948230007be8bd9

and here successful:
https://app.netlify.com/sites/netlify-plugin-submit-sitemap/deploys/5ed92b958439ab0008593d82

If there is anything that you think can be improved, let me know. Thanks a lot!

**Comment by ehmicky** [comment]
Thanks a lot for going through the code review!
There is one small thing left: https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/issues/4#issuecomment-639087979
But after this, it's ready to ship! :tada:

**Comment by cdeleeuwe** [comment]
@ehmicky Great, thanks for reviewing. I have pushed an update with a fix. If there is anything else, feel free to let me know :).

**Pull request merged**
