### PR TITLE
Upgrade netlify-plugin-html-validate to 1.0.0

### PR DESCRIPTION
**Pull request by oliverroick**
Thanks for contributing the Netlify plugins directory!

**Are you adding a plugin or updating one?**

- [ ] Adding a plugin
- [x] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**

Successful build using the new version: https://app.netlify.com/sites/oliverroick/deploys/60310535fe316e00079604d5

### CODE REVIEW

**Comment by JGAntunes** [comment]
Hey @oliverroick 👋 thanks for the update and supporting this plugin. About the release, given - https://gitlab.com/html-validate/html-validate/-/blob/master/CHANGELOG.md#-breaking-changes, am I correct in assuming that Netlify users who rely on this plugin might see some breaking changes if they're providing their own config via `inputs`?

**Comment by oliverroick** [comment]
Hey @JGAntunes,

> am I correct in assuming that Netlify users who rely on this plugin might see some breaking changes if they're providing their own config via inputs

Yes, that's correct. There may be issues if users apply a custom config and if that config does not explicitly extend a default configuration.

**Comment by JGAntunes** [comment]
Thanks for clearing that out @oliverroick.

One limitation our plugin system currently has is the inability to handle breaking changes clearly and cleanly. Meaning, users relying on this plugin, who installed it via the UI and provided a configuration via `inputs` (however small this group may be) could see broken builds/unexpected behaviour if we were to update our `plugins.json` reference with your latest release. We're actively working on supporting breaking changes, and we'll follow up with this PR once we have a solution in place.

Meanwhile, you and anyone that is looking for a way to use the latest version of the plugin can do so by adding it to the `netlify.toml` and adding it as a `package.json` dependency - https://docs.netlify.com/configure-builds/build-plugins/#file-based-installation.

We'll keep you posted :+1:

**Comment by ehmicky** [comment]
Hi @oliverroick,

We have just added a `compatibility` field which solves the breaking changes problem in this PR. :tada: 
  - Current users of `netlify-plugin-html-validate` who installed the plugin in the UI will remain pinned to `0.1.1`.
  - Current users who installed the plugin in `package.json` will keep using the version specified in it, i.e. they will also be pinned to `0.1.1`. 
  - Users who remain on `0.1.1` are shown a warning message in their build logs that recommends upgrading the plugin. Users can do so by uninstalling then re-installing the plugin in the UI. In the future, we will add a UI action to do it in a single step.  
  - New users will use `1.0.0`. 

Please feel free to share any feedback!

**Pull request closed without merging**
